#!/bin/bash
#
# run_all_tests.sh
#
# Automation to run all ts_store stress tests (001-007 TS/XS + flags).
# Now exercises double-buffered persistence (async) for *every* test, once with
# BinaryEventSink and once with JTextEventSink (via --persist).
#
# Output logs + persist artifacts go under:
#   test_results/binary_logs/TS_STORE_TEST_001_TS/
#   test_results/jText_logs/TS_STORE_TEST_001_TS/
#   (and same for all other tests; flags gets logs in both for structure)
#
# A rich summary document is (re)generated at the project root (or under test_results)
# with OS, compiler column, compile times, per-run start/stop/duration, record counts,
# which log type was faster per scenario, links, Config settings, etc.
#
# Usage:
#   ./scripts/run_all_tests.sh --compiler gcc --output yes
#   ./scripts/run_all_tests.sh --compiler clang --output yes
#   ./scripts/run_all_tests.sh   # defaults to gcc, output=yes
#
# After runs (run once per compiler to populate both), see the summary and
# test_results/ tree. README.md links to the summary.
#
# Note: GCC path uses "scl enable gcc-toolset-15". Always passes --interactive=0 --color=0.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Strip ANSI color escape sequences. This makes the saved .log files clean plain text
# (good for Markdown, GitHub, Vim, editors, git grep, etc.) while still allowing
# pretty colors when a human runs a test binary directly in a real terminal.
strip_ansi() {
    sed -r 's/\x1B\[[0-9;]*[mGK]//g'
}

# Map e.g. "ts_store_005_TS" -> "TS_STORE_TEST_005_TS"
# "ts_store_flags" -> "TS_STORE_TEST_flags"
test_to_subdir_name() {
    local t="$1"
    if [[ "$t" == "ts_store_flags" ]]; then
        echo "TS_STORE_TEST_flags"
    else
        local base="${t#ts_store_}"
        echo "TS_STORE_TEST_${base}"
    fi
}

# Extract a rough "number of records" from a captured test log (best effort).
# For massive tests this is TOTAL*RUNS.
extract_record_count() {
    local logf="$1"
    # Try several patterns the tests emit
    local n
    n=$(grep -oE 'FINAL MASSIVE TEST — [0-9,]+ entries| [0-9,]+ entries × [0-9]+ runs|All [0-9,]+ (entries|ENTRIES)|with [0-9,]+ entries' "$logf" 2>/dev/null | head -1 | grep -oE '[0-9,]+' | tr -d ',' | head -1 || true)
    if [[ -z "$n" ]]; then
        n=$(grep -oE 'TOTAL[^0-9]*[0-9,]+|expected: [0-9,]+' "$logf" 2>/dev/null | head -1 | grep -oE '[0-9,]+' | tr -d ',' | head -1 || true)
    fi
    echo "${n:-?}"
}

# Generate the rich markdown summary document.
# Scans test_results/... for .meta + .log files (supports multiple compilers).
# Includes OS info, compile time, compiler column, faster log per scenario, etc.
generate_test_summary() {
    local out_file="$1"
    local compiler="$2"
    local compiler_display="$3"
    local build_info="$4"
    local results_base="$5"
    local passed="$6"
    local failed="$7"
    local total_scenarios="$8"

    local now=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    local os_pretty="unknown"
    if [[ -r /etc/os-release ]]; then
        # shellcheck disable=SC1091
        . /etc/os-release 2>/dev/null || true
        os_pretty="${PRETTY_NAME:-$NAME $VERSION}"
    else
        os_pretty=$(uname -sr)
    fi

    # Header
    cat > "$out_file" <<HDR
# TS_STORE Test Results Summary

**Date**: $now  
**OS**: $os_pretty  
**Summary generated by**: scripts/run_all_tests.sh (double-buffered persist on all tests)

## Build / Compile Info (this compiler run)
**Compiler**: $compiler_display  
**Build**: $build_info

HDR

    # Collect runs by scanning metas
    # We'll build rows and also compute per-(test,compiler) faster logtype
    declare -a rows=()
    declare -A scenario_data=()   # key=test|compiler  value="binary_dur jtext_dur binary_rec jtext_rec"

    for logtype_dir in "$results_base/binary_logs" "$results_base/jText_logs"; do
        [[ -d "$logtype_dir" ]] || continue
        for sub in "$logtype_dir"/TS_STORE_TEST_* ; do
            [[ -d "$sub" ]] || continue
            local subname=$(basename "$sub")
            for meta in "$sub"/*.meta ; do
                [[ -f "$meta" ]] || continue
                # source the meta (simple key=value)
                local COMPILER TEST LOGTYPE SUBDIR START STOP DURATION_SEC STATUS RECORDS
                COMPILER=""; TEST=""; LOGTYPE=""; SUBDIR=""; START=""; STOP=""; DURATION_SEC=""; STATUS=""; RECORDS="?"
                # shellcheck disable=SC1090
                . "$meta" 2>/dev/null || true

                # Measure actual persist file size(s) on disk for this run
                local persist_bytes=0
                for f in "$logtype_dir/$SUBDIR"/persist*; do
                    if [[ -f "$f" ]]; then
                        local s
                        s=$(stat -c%s "$f" 2>/dev/null || echo 0)
                        persist_bytes=$((persist_bytes + s))
                    fi
                done
                local persist_human
                if command -v numfmt >/dev/null 2>&1; then
                    persist_human=$(numfmt --to=iec-i --suffix=B --format="%.1f" "$persist_bytes" 2>/dev/null || echo "${persist_bytes}B")
                else
                    persist_human="${persist_bytes}B"
                fi
                local persist_mbs="N/A"
                if [[ "$DURATION_SEC" =~ ^[0-9]+$ && "$DURATION_SEC" -gt 0 && "$persist_bytes" -gt 0 ]]; then
                    persist_mbs=$(echo "scale=1; $persist_bytes / 1024 / 1024 / $DURATION_SEC" | bc -l 2>/dev/null || echo "N/A")
                elif [[ "$persist_bytes" -gt 0 && "$DURATION_SEC" == "0" ]]; then
                    persist_mbs="instant"
                fi

                local lt_short="$LOGTYPE"
                # relative link from summary at project root
                local rel_path="test_results/$(basename "$logtype_dir")/$SUBDIR/${COMPILER}.log"
                local log_link="[$lt_short log]($rel_path)"
                local persist_note=""
                if [[ "$LOGTYPE" == "binary" ]]; then
                    persist_note="(.bin under subdir)"
                else
                    persist_note="(.jtext + _Ints.jtext + _Floats.jtext under subdir)"
                fi

                rows+=("| ${COMPILER} | ${SUBDIR} | ${LOGTYPE} | ${RECORDS:-?} | ${START:-?} | ${STOP:-?} | ${DURATION_SEC}s | ${persist_human} | ${persist_mbs} MB/s | ${STATUS} | ${log_link} ${persist_note} |")

                # for faster + smaller computation: store b_dur b_size b_rec j_dur j_size j_rec
                local key="${SUBDIR}|${COMPILER}"
                local cur="${scenario_data[$key]:-}"
                local b_dur="" b_size="" b_rec=""
                local j_dur="" j_size="" j_rec=""
                if [[ -n "$cur" ]]; then
                    read -r b_dur b_size b_rec j_dur j_size j_rec <<< "$cur"
                fi
                if [[ "$LOGTYPE" == "binary" ]]; then
                    b_dur="${DURATION_SEC}"
                    b_size="${persist_bytes}"
                    b_rec="${RECORDS}"
                else
                    j_dur="${DURATION_SEC}"
                    j_size="${persist_bytes}"
                    j_rec="${RECORDS}"
                fi
                scenario_data[$key]="${b_dur} ${b_size} ${b_rec} ${j_dur} ${j_size} ${j_rec}"
            done
        done
    done

    # Main table
    cat >> "$out_file" <<'TABLE'

## Test Run Summary (all scenarios)

| Compiler | Test Name | Log Type | Records | Start (UTC) | Stop (UTC) | Duration | Persist Size | Persist MB/s | Status | Log |
|----------|-----------|----------|---------|-------------|------------|----------|--------------|--------------|--------|-----|
TABLE

    # Sort rows roughly (by compiler then test) - simple lexical is ok
    printf "%s\n" "${rows[@]}" | sort >> "$out_file"

    cat >> "$out_file" <<FOOT1

**Total scenarios this run**: $total_scenarios (passed: $passed, failed: $failed)

**Persist Size / MB/s**: measured from the actual on-disk files written by the persistence layer (binary = one .bin; jText = sum of .jtext + .sql sidecars). Rate = size / full test duration (includes hot path + verification + async background drain + finalize). For 0s runs the rate is N/A.

FOOT1

    # Faster log per scenario (per compiler)
    cat >> "$out_file" <<'FASTER'

## Which log type was faster / smaller? (per test + compiler)
(time = full binary wall time including async persist drain; size = total on-disk persist artifacts)

FASTER

    local any_comp=0
    for key in "${!scenario_data[@]}"; do
        any_comp=1
        local tname="${key%%|*}"
        local cname="${key##*|}"
        local data="${scenario_data[$key]}"
        read -r bdur bsize brec jdur jsize jrec <<< "$data"

        local time_line=""
        if [[ "$bdur" =~ ^[0-9]+$ && "$jdur" =~ ^[0-9]+$ ]]; then
            if (( bdur < jdur )); then
                time_line="**binary** faster (${bdur}s vs ${jdur}s"
            elif (( jdur < bdur )); then
                time_line="**jText** faster (${jdur}s vs ${bdur}s"
            else
                time_line="tie (${bdur}s"
            fi
        fi

        local size_line=""
        if [[ "$bsize" =~ ^[0-9]+$ && "$jsize" =~ ^[0-9]+$ && "$bsize" -gt 0 && "$jsize" -gt 0 ]]; then
            local delta_mb=$(( (bsize > jsize ? bsize - jsize : jsize - bsize) / 1024 / 1024 ))
            if (( bsize < jsize )); then
                size_line=", binary smaller by ${delta_mb}MB"
            elif (( jsize < bsize )); then
                size_line=", jText smaller by ${delta_mb}MB"
            else
                size_line=", same size"
            fi
        fi

        local rec_info="~${brec:-?} rec"
        if [[ -n "$time_line" || -n "$size_line" ]]; then
            echo "- **$tname** ($cname): ${time_line}${size_line}) | ${rec_info}" >> "$out_file"
        fi
    done
    if (( any_comp == 0 )); then
        echo "(No comparative data yet — run for both gcc and clang.)" >> "$out_file"
    fi

    # Notes + Configs
    cat >> "$out_file" <<'NOTES'

## Notes
- All tests now attach a `DoubleBufferedWriter` + chosen sink (`BinaryEventSink` or `JTextEventSink`) for asynchronous background persistence. Hot path remains fast.
- Persist artifacts (`.bin` or the 3 `.jtext` files) are written using the `--base-name` passed by the runner so they land inside the corresponding `test_results/*/TS_STORE_TEST_.../` subdirectory.
- `Records` are best-effort parsed from test output (for 005/007 this is typically 1,000,000 × 50 = 50M per invocation).
- Persist Size and Persist MB/s columns: actual bytes written to the log files on disk after each (test, logtype) run. Rate is observed throughput (size / wall duration). All tests now really persist via the double-buffered writer.
- Compile/build time is for the full set of test binaries for that compiler (Release + jText enabled).
- Run the script once per compiler (`--compiler gcc` then `--compiler clang`) to populate both columns and the "faster" comparisons.
- Legacy `results/<compiler>/` tree may still exist from prior versions; new canonical location is `test_results/`.

## Config settings used by the tests (LogConfig)
- 001/002/003/006/007 (TS): `ts_store_config<true, 6, 20, 43, 9, 6, false>`
- 001/002/003/006/007 (XS): `ts_store_config<false, 6, 20, 43, 9, 6, false>`
- 004 (TS): `ts_store_config<true, 6, 20, 75, 9, 6, false>` (main) + result config
- 004 (XS): `ts_store_config<false, 6, 20, 75, 9, 6, false>`
- 005 (TS): `ts_store_config<true, 6, 20, 43, 9, 6, false>` (250 threads × 4000 × 50 runs)
- 005 (XS): `ts_store_config<false, 6, 20, 43, 9, 6, false>`
- flags: standalone `TsStoreFlags` unit test (no store / no persist)

See main [README.md](README.md) and the test sources under `tests/` for details.

NOTES

    echo "Summary updated: $out_file"
}

COMPILER="gcc"
OUTPUT_MODE="yes"  # yes = show on console (tee), no = silent to logs only

usage() {
    echo "Usage: $0 [--compiler gcc|clang] [--output yes|no]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case $1 in
        --compiler)
            COMPILER="$2"
            shift 2
            ;;
        --output)
            OUTPUT_MODE="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

if [[ "$COMPILER" != "gcc" && "$COMPILER" != "clang" ]]; then
    echo "Compiler must be gcc or clang"
    usage
fi

if [[ "$OUTPUT_MODE" != "yes" && "$OUTPUT_MODE" != "no" ]]; then
    echo "--output must be yes or no"
    usage
fi

if [[ "$COMPILER" == "gcc" ]]; then
    COMPILER_DISPLAY="GCC 15 (gcc-toolset-15)"
else
    COMPILER_DISPLAY="Clang 21.1 (Red Hat)"
fi

echo "=== ts_store All Stress Tests Runner (double-buffered persist for ALL tests) ==="
echo "Compiler: $COMPILER"
echo "Output mode: $OUTPUT_MODE (console visible: $OUTPUT_MODE)"
echo "Primary output: test_results/binary_logs/ + jText_logs/ + TS_STORE_Test_Summary.md"
echo

# Determine build dir and how to invoke cmake/build
BUILD_DIR="$PROJECT_ROOT/build-results-$COMPILER"
CMAKE_CMD="cmake"
BUILD_CMD="cmake --build . --target"

if [[ "$COMPILER" == "gcc" ]]; then
    CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DTS_STORE_ENABLE_JTEXT_PERSIST=ON"
    # Enable jText for the big double-buffer tests (005/007) so they can use
    # JTextSplitEventLog via JTextEventSink, producing separate _Ints.jtext and
    # _Floats.jtext files with all the metric data (in addition to the main log).
    # The stress tests (001-007) are always built.
else
    CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DTS_STORE_ENABLE_JTEXT_PERSIST=ON"
fi

echo "Using build dir: $BUILD_DIR"

# Only reconfigure/rebuild if the expected binaries are missing (to speed up repeated runs)
NEED_BUILD=0
for t in ts_store_001_TS ts_store_001_XS ts_store_002_TS ts_store_002_XS ts_store_003_TS ts_store_003_XS ts_store_004_TS ts_store_004_XS ts_store_005_TS ts_store_005_XS ts_store_006_TS ts_store_006_XS ts_store_007_TS ts_store_007_XS ts_store_flags; do
    if [[ ! -x "$BUILD_DIR/$t" ]]; then
        NEED_BUILD=1
        break
    fi
done

# Force rebuild if key sources (tests, CMake, options parser) are newer than the binaries.
# This ensures the new --persist / double-buffer attach code is compiled in for all tests.
for src in "$PROJECT_ROOT/tests/ts_store_001/test_001_TS.cpp" \
           "$PROJECT_ROOT/CMakeLists.txt" \
           "$PROJECT_ROOT/include/beman/ts_store/ts_store_headers/impl_details/test_options.hpp" ; do
    if [[ -f "$src" && -f "$BUILD_DIR/ts_store_001_TS" && "$src" -nt "$BUILD_DIR/ts_store_001_TS" ]]; then
        NEED_BUILD=1
        echo "Source newer than existing binaries ($src) — forcing clean build"
        break
    fi
done

BUILD_START_TS=""
BUILD_END_TS=""
BUILD_DURATION_SEC="skipped"

if [[ $NEED_BUILD -eq 1 ]]; then
    echo "Binaries missing or first run — cleaning and building..."
    BUILD_START_TS=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    BUILD_START_EP=$(date +%s)
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    CONFIGURE_CMD="$CMAKE_CMD $CMAKE_ARGS '$PROJECT_ROOT'"

    if [[ "$COMPILER" == "gcc" ]]; then
        scl enable gcc-toolset-15 -- bash -c "$CONFIGURE_CMD"
    else
        eval "$CONFIGURE_CMD"
    fi

    echo "Building all stress test binaries..."
    TARGETS="ts_store_001_TS ts_store_001_XS ts_store_002_TS ts_store_002_XS ts_store_003_TS ts_store_003_XS ts_store_004_TS ts_store_004_XS ts_store_005_TS ts_store_005_XS ts_store_006_TS ts_store_006_XS ts_store_007_TS ts_store_007_XS ts_store_flags"

    if [[ "$COMPILER" == "gcc" ]]; then
        scl enable gcc-toolset-15 -- bash -c "cmake --build . --target $TARGETS -j\$(nproc)"
    else
        cmake --build . --target $TARGETS -j$(nproc)
    fi
    BUILD_END_TS=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
    BUILD_END_EP=$(date +%s)
    BUILD_DURATION_SEC=$((BUILD_END_EP - BUILD_START_EP))
    echo "Build complete. (duration: ${BUILD_DURATION_SEC}s)"
else
    echo "All test binaries already present in $BUILD_DIR — skipping rebuild."
    cd "$BUILD_DIR"
fi

# test_results/ layout (per user request)
TEST_RESULTS_BASE="$PROJECT_ROOT/test_results"
BINARY_LOGS="$TEST_RESULTS_BASE/binary_logs"
JTEXT_LOGS="$TEST_RESULTS_BASE/jText_logs"
mkdir -p "$BINARY_LOGS"
mkdir -p "$JTEXT_LOGS"

# === New structured run: every test x2 (binary + jtext), logs + persist artifacts under test_results/ ===

# List of tests in order (all now get double-buffered persist)
declare -a TESTS=(
    "ts_store_001_TS"
    "ts_store_001_XS"
    "ts_store_002_TS"
    "ts_store_002_XS"
    "ts_store_003_TS"
    "ts_store_003_XS"
    "ts_store_004_TS"
    "ts_store_004_XS"
    "ts_store_005_TS"
    "ts_store_005_XS"
    "ts_store_006_TS"
    "ts_store_006_XS"
    "ts_store_007_TS"
    "ts_store_007_XS"
    "ts_store_flags"
)

echo
echo "=== Running all tests (double-buffered async persist for every test) ==="
echo "Binary logs : $BINARY_LOGS/"
echo "jText logs  : $JTEXT_LOGS/"
echo "Each test subdir (e.g. TS_STORE_TEST_005_TS) will contain ${COMPILER}.log + persist.* files"
echo

TOTAL_SCENARIOS=$(( ${#TESTS[@]} * 2 ))
RUN_PASSED=0
RUN_FAILED=0

# Per-compiler build info for the summary
if [[ "$BUILD_DURATION_SEC" == "skipped" ]]; then
  BUILD_INFO="Build: skipped (binaries up to date)"
else
  BUILD_INFO="Build duration: ${BUILD_DURATION_SEC}s (start: ${BUILD_START_TS:-N/A}, end: ${BUILD_END_TS:-N/A})"
fi

for test in "${TESTS[@]}"; do
    bin="./$test"
    if [[ ! -x "$bin" ]]; then
        echo "ERROR: binary $bin not found"
        for persist_val in binary jtext; do
            if [[ "$persist_val" == "jtext" ]]; then
                logdir_name="jText_logs"
            else
                logdir_name="binary_logs"
            fi
            sdir=$(test_to_subdir_name "$test")
            ldir="$TEST_RESULTS_BASE/$logdir_name/$sdir"
            mkdir -p "$ldir"
            echo "ERROR: binary $bin not found or not executable (logtype=$persist_val)" > "$ldir/${COMPILER}.log"
            echo "=== TEST RUN FAILED (logtype=$persist_val) ===" >> "$ldir/${COMPILER}.log"
        done
        RUN_FAILED=$((RUN_FAILED + 2))
        continue
    fi

    for persist_val in binary jtext; do
        logtype="$persist_val"
        if [[ "$persist_val" == "jtext" ]]; then
            logdir_name="jText_logs"
        else
            logdir_name="binary_logs"
        fi
        sdir=$(test_to_subdir_name "$test")
        ldir="$TEST_RESULTS_BASE/$logdir_name/$sdir"
        mkdir -p "$ldir"
        persist_base="$ldir/persist"
        run_log="$ldir/${COMPILER}.log"

        echo "Running $test (logtype=$logtype) ... -> $run_log"

        start_ts=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        start_ep=$(date +%s)

        if [[ "$OUTPUT_MODE" == "yes" ]]; then
            "$bin" --interactive=0 --color=0 --persist="$logtype" --base-name="$persist_base" < /dev/null 2>&1 \
                | tee >(strip_ansi > "$run_log")
            bin_status=${PIPESTATUS[0]}
        else
            "$bin" --interactive=0 --color=0 --persist="$logtype" --base-name="$persist_base" < /dev/null 2>&1 \
                | strip_ansi > "$run_log"
            bin_status=${PIPESTATUS[0]}
        fi

        stop_ts=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        stop_ep=$(date +%s)
        dur_sec=$((stop_ep - start_ep))

        if [ $bin_status -ne 0 ]; then
            echo "  -> $test / $logtype FAILED (${dur_sec}s)"
            echo "=== TEST RUN FAILED (logtype=$logtype, duration=${dur_sec}s) ===" >> "$run_log"
            RUN_FAILED=$((RUN_FAILED + 1))
        else
            echo "  -> $test / $logtype PASSED (${dur_sec}s)"
            echo "=== TEST RUN PASSED (logtype=$logtype, duration=${dur_sec}s) ===" >> "$run_log"
            RUN_PASSED=$((RUN_PASSED + 1))
        fi

        # Write a tiny meta for easy summary scanning
        # Also capture persist size right after run (for cases where summary is regenerated later)
        pbytes=0
        for f in "$ldir"/persist*; do
            [[ -f "$f" ]] && pbytes=$((pbytes + $(stat -c%s "$f" 2>/dev/null || echo 0)))
        done
        cat > "$ldir/${COMPILER}_${logtype}.meta" <<META
COMPILER=${COMPILER}
TEST=${test}
LOGTYPE=${logtype}
SUBDIR=${sdir}
START=${start_ts}
STOP=${stop_ts}
DURATION_SEC=${dur_sec}
STATUS=$([ $bin_status -eq 0 ] && echo PASS || echo FAIL)
RECORDS=$(extract_record_count "$run_log")
PERSIST_SIZE_BYTES=${pbytes}
META
    done
done

echo
echo "=== All test scenarios completed ==="
echo "Passed: $RUN_PASSED / $TOTAL_SCENARIOS"
echo "Failed: $RUN_FAILED / $TOTAL_SCENARIOS"
echo "Structured logs + persist files under: $TEST_RESULTS_BASE/"
echo

# Generate (or update) the rich summary document at the project root / test_results
SUMMARY_FILE="$PROJECT_ROOT/TS_STORE_Test_Summary.md"
generate_test_summary "$SUMMARY_FILE" "$COMPILER" "$COMPILER_DISPLAY" "$BUILD_INFO" "$TEST_RESULTS_BASE" "$RUN_PASSED" "$RUN_FAILED" "$TOTAL_SCENARIOS"

echo "Rich summary written to: $SUMMARY_FILE"
echo
echo "Done."