#include "SqlEventSink.hpp"

#include <filesystem>
#include <sstream>
#include <iomanip>

namespace fs = std::filesystem;
namespace jac::ts_store::inline_v001 {

static constexpr uint64_t KEEPER_MASK    = 1ULL << 1;
static constexpr uint64_t DATABASE_MASK = 1ULL << 2;

SqlEventSink::SqlEventSink(std::string_view base_name,
                           size_t int_count,
                           size_t dbl_count,
                           PersistMode mode,
                           bool write_debug_sql)
    : int_count_(int_count)
    , dbl_count_(dbl_count)
    , mode_(mode)
{
    table_base_ = fs::path(std::string(base_name)).filename().string();
    if (table_base_.empty()) table_base_ = "persist";

    db_path_ = std::string(base_name) + ".db";
    debug_path_ = std::string(base_name) + ".sql";  // debug insert statements for inspection/replay

    try {
        db_ = std::make_unique<Sqlite>(db_path_);
    } catch (const std::exception& ex) {
        throw std::runtime_error(std::string("SqlEventSink failed to open DB '") + db_path_ + "': " + ex.what());
    }

    if (write_debug_sql) {
        debug_sql_.open(debug_path_, std::ios::out | std::ios::app);
        if (debug_sql_.is_open()) {
            debug_sql_ << "-- Direct SQL debug file generated by ts_store SqlEventSink\n";
            debug_sql_ << "-- DB: " << db_path_ << "\n";
            debug_sql_ << "-- Base: " << base_name << "\n\n";
        }
    }

    ensure_tables_and_prepare();
}

SqlEventSink::~SqlEventSink() {
    try {
        finalize();
    } catch (...) {}
}

void SqlEventSink::ensure_tables_and_prepare() {
    // Main table
    {
        std::ostringstream oss;
        oss << "CREATE TABLE IF NOT EXISTS " << table_base_ << " (\n"
            << "    id BIGINT PRIMARY KEY,\n"
            << "    thread_id BIGINT,\n"
            << "    per_thread_event_id BIGINT,\n"
            << "    flags_raw BIGINT,\n"
            << "    category TEXT,\n"
            << "    payload TEXT,\n"
            << "    timestamp_us BIGINT\n"
            << ");\n";
        db_->exec(oss.str());
    }

    if (int_count_ > 0) {
        std::ostringstream oss;
        oss << "CREATE TABLE IF NOT EXISTS " << table_base_ << "_ints (\n"
            << "    id BIGINT PRIMARY KEY,\n";
        for (size_t k = 0; k < int_count_; ++k) {
            oss << "    int" << k << " BIGINT";
            if (k + 1 < int_count_) oss << ",";
            oss << "\n";
        }
        oss << "    , thread_id BIGINT,\n"
            << "    per_thread_event_id BIGINT,\n"
            << "    flags_raw BIGINT,\n"
            << "    timestamp_us BIGINT\n"
            << ");\n";
        db_->exec(oss.str());
    }

    if (dbl_count_ > 0) {
        std::ostringstream oss;
        oss << "CREATE TABLE IF NOT EXISTS " << table_base_ << "_floats (\n"
            << "    id BIGINT PRIMARY KEY,\n";
        for (size_t k = 0; k < dbl_count_; ++k) {
            oss << "    dbl" << k << " REAL";
            if (k + 1 < dbl_count_) oss << ",";
            oss << "\n";
        }
        oss << "    , thread_id BIGINT,\n"
            << "    per_thread_event_id BIGINT,\n"
            << "    flags_raw BIGINT,\n"
            << "    timestamp_us BIGINT\n"
            << ");\n";
        db_->exec(oss.str());
    }

    // Prepare INSERT statements (use OR IGNORE for tolerance)
    {
        std::ostringstream oss;
        oss << "INSERT OR IGNORE INTO " << table_base_
            << " (id, thread_id, per_thread_event_id, flags_raw, category, payload, timestamp_us) "
            << "VALUES (?, ?, ?, ?, ?, ?, ?);";
        stmt_main_ = std::make_unique<Sqlite::Statement>(*db_, oss.str());
    }

    if (int_count_ > 0) {
        std::ostringstream oss;
        oss << "INSERT OR IGNORE INTO " << table_base_ << "_ints (id";
        for (size_t k = 0; k < int_count_; ++k) oss << ", int" << k;
        oss << ", thread_id, per_thread_event_id, flags_raw, timestamp_us) VALUES (?";
        for (size_t k = 0; k < int_count_; ++k) oss << ", ?";
        oss << ", ?, ?, ?, ?);";
        stmt_ints_ = std::make_unique<Sqlite::Statement>(*db_, oss.str());
    }

    if (dbl_count_ > 0) {
        std::ostringstream oss;
        oss << "INSERT OR IGNORE INTO " << table_base_ << "_floats (id";
        for (size_t k = 0; k < dbl_count_; ++k) oss << ", dbl" << k;
        oss << ", thread_id, per_thread_event_id, flags_raw, timestamp_us) VALUES (?";
        for (size_t k = 0; k < dbl_count_; ++k) oss << ", ?";
        oss << ", ?, ?, ?, ?);";
        stmt_dbls_ = std::make_unique<Sqlite::Statement>(*db_, oss.str());
    }
}

void SqlEventSink::write_batch(std::span<const PersistedEvent> batch) {
    if (!db_ || batch.empty()) return;

    db_->begin();

    for (const auto& e : batch) {
        if (mode_ == PersistMode::KeeperOnly) {
            if ((e.flags & KEEPER_MASK) == 0) continue;
        } else if (mode_ == PersistMode::DatabaseOnly) {
            if ((e.flags & DATABASE_MASK) == 0) continue;
        }
        insert_event(e);
    }

    db_->commit();
}

void SqlEventSink::insert_event(const PersistedEvent& e) {
    // Main table (always prepared)
    stmt_main_->bind(
        static_cast<int64_t>(e.event_id),
        static_cast<int64_t>(e.thread_id),
        static_cast<int64_t>(e.per_thread_event_id),
        static_cast<int64_t>(e.flags),
        e.category,
        e.payload,
        static_cast<int64_t>(e.timestamp_us)
    );
    while (stmt_main_->step()) {}
    stmt_main_->reset();
    ++main_rows_inserted_;

    write_debug_insert(e);

    // Ints table
    if (stmt_ints_) {
        stmt_ints_->reset();
        stmt_ints_->clear_bindings();
        int idx = 1;
        stmt_ints_->bind_int64(idx++, static_cast<int64_t>(e.event_id));
        for (size_t k = 0; k < int_count_; ++k) {
            int64_t v = (k < e.int_metrics.size()) ? e.int_metrics[k] : 0;
            stmt_ints_->bind_int64(idx++, v);
        }
        stmt_ints_->bind_int64(idx++, static_cast<int64_t>(e.thread_id));
        stmt_ints_->bind_int64(idx++, static_cast<int64_t>(e.per_thread_event_id));
        stmt_ints_->bind_int64(idx++, static_cast<int64_t>(e.flags));
        stmt_ints_->bind_int64(idx++, static_cast<int64_t>(e.timestamp_us));
        while (stmt_ints_->step()) {}
    }

    // Dbls table
    if (stmt_dbls_) {
        stmt_dbls_->reset();
        stmt_dbls_->clear_bindings();
        int idx = 1;
        stmt_dbls_->bind_int64(idx++, static_cast<int64_t>(e.event_id));
        for (size_t k = 0; k < dbl_count_; ++k) {
            double v = (k < e.dbl_metrics.size()) ? e.dbl_metrics[k] : 0.0;
            stmt_dbls_->bind_double(idx++, v);
        }
        stmt_dbls_->bind_int64(idx++, static_cast<int64_t>(e.thread_id));
        stmt_dbls_->bind_int64(idx++, static_cast<int64_t>(e.per_thread_event_id));
        stmt_dbls_->bind_int64(idx++, static_cast<int64_t>(e.flags));
        stmt_dbls_->bind_int64(idx++, static_cast<int64_t>(e.timestamp_us));
        while (stmt_dbls_->step()) {}
    }
}

void SqlEventSink::flush() {
    if (debug_sql_.is_open()) {
        debug_sql_.flush();
    }
}

void SqlEventSink::finalize() {
    if (finalized_) return;
    if (debug_sql_.is_open()) {
        debug_sql_ << "\n-- End of direct SQL debug run\n";
        debug_sql_.close();
    }
    stmt_main_.reset();
    stmt_ints_.reset();
    stmt_dbls_.reset();
    db_.reset();
    finalized_ = true;
}

void SqlEventSink::write_debug_insert(const PersistedEvent& e) {
    if (!debug_sql_.is_open()) return;

    auto esc = [this](const std::string& s) { return escape_for_sql(s); };

    debug_sql_ << "INSERT OR IGNORE INTO " << table_base_ << " (id, thread_id, per_thread_event_id, flags_raw, category, payload, timestamp_us) VALUES ("
               << e.event_id << ", " << e.thread_id << ", " << e.per_thread_event_id << ", " << e.flags << ", '"
               << esc(e.category) << "', '" << esc(e.payload) << "', " << e.timestamp_us << ");\n";

    if (int_count_ > 0) {
        debug_sql_ << "INSERT OR IGNORE INTO " << table_base_ << "_ints (id";
        for (size_t k = 0; k < int_count_; ++k) debug_sql_ << ", int" << k;
        debug_sql_ << ", thread_id, per_thread_event_id, flags_raw, timestamp_us) VALUES ("
                   << e.event_id;
        for (size_t k = 0; k < int_count_; ++k) {
            int64_t v = (k < e.int_metrics.size()) ? e.int_metrics[k] : 0;
            debug_sql_ << ", " << v;
        }
        debug_sql_ << ", " << e.thread_id << ", " << e.per_thread_event_id << ", " << e.flags << ", " << e.timestamp_us << ");\n";
    }

    if (dbl_count_ > 0) {
        debug_sql_ << "INSERT OR IGNORE INTO " << table_base_ << "_floats (id";
        for (size_t k = 0; k < dbl_count_; ++k) debug_sql_ << ", dbl" << k;
        debug_sql_ << ", thread_id, per_thread_event_id, flags_raw, timestamp_us) VALUES ("
                   << e.event_id;
        for (size_t k = 0; k < dbl_count_; ++k) {
            double v = (k < e.dbl_metrics.size()) ? e.dbl_metrics[k] : 0.0;
            debug_sql_ << ", " << std::fixed << std::setprecision(10) << v;
        }
        debug_sql_ << ", " << e.thread_id << ", " << e.per_thread_event_id << ", " << e.flags << ", " << e.timestamp_us << ");\n";
    }
}

std::string SqlEventSink::escape_for_sql(const std::string& s) const {
    std::string out;
    out.reserve(s.size() * 2);
    for (char c : s) {
        if (c == '\'') out += "''";
        else out += c;
    }
    return out;
}

} // namespace jac::ts_store::inline_v001